### ISSUE TITLE
Issue with the graph material being overwritten once you have version control running with it (Git or Collab)

### ISSUE THREAD

**Issue by Tayx94** [Tayx94/graphy#2]
I haven't been able to reproduce this error, but if someone does please report!

**Comment by petereichinger** [comment]
Do you mean the '.mat' file in the project?

**Comment by Tayx94** [comment]
I guess so! It was reported by a user on reddit, but I haven't had that happen to me.

**Comment by petereichinger** [comment]
AFAIK this happens when at runtime in the editor the sharedMaterial of any renderer is modified. I prevent this in my current prjoject by instantiating the material before using it. I'm not sure if there is a better way.

If you want I can take a look at it, but I'll probably can get to it next week.

**Comment by Tayx94** [comment]
The thing is, I'm actually doing that, on startup I instantiate a new material for each graph, so maybe the problem was on his end. Just wanted to know if this was happening to other people as well.

**Comment by NicholasSheehan** [comment]
Just a thought, could there be a setting in the OP's .gitignore that could be causing the issue? (*.meta comes to mind)

**Comment by Tayx94** [comment]
That is a good point @NicholasSheehan , I'll close this issue for now, and reopen it in the future if the problem persists and is caused by Graphy.
